name = "aidevelo-co"
compatibility_date = "2024-09-19"

[env.production]
name = "aidevelo-co"

[[pages_builds]]
command = "echo 'Building for production'"
publish = "."

[build]
command = "echo 'Building application'"
publish = "."
